data:
  raw:
    ravdess_speech: data/ravdess/speech/
    ravdess_song: data/ravdess/song/
    crema_d: data/crema-d/
    deam: ../drive/MyDrive/data/deam/audio/
  processed: data/processed/
audio:
  n_mfcc: 40
  max_pad_len: 174
  sampling_rate: 22050
model:
  name: emotitune_cnn.pth
  dir: models/
training:
  batch_size: 32
  learning_rate: 0.001
  num_epochs: 30
  patience: 5
  val_split: 0.2
  seed: 42
